### ISSUE TITLE
No sound or no image 

### ISSUE THREAD

**Issue by WatcherNL** [watchedcom/watched-js#18]
When watching the UK content I have sometimes no image but only sound. And when is switch from player then it's the other way around. 
Is there a solution? 
Oh it's mostly with the Food network! 

Greetings from the Netherlands 

- **Only** post issues related to the WATCHED app or the WATCHED SDK.

- We do **not** give support for **3rd party addons**. Try to contact the addon creator.

- If you have an issue with one of [official addons](https://github.com/watchedcom) create an issue in the corresponding repo.

**Comment by maximilize** [comment]
Hello,

please see our issue rules: *We do not give support for 3rd party addons. Try to contact the addon creator.*
