### ISSUE TITLE
Iptv crashing issue

### ISSUE THREAD

**Issue by freddyumari** [watchedcom/watched-js#28]
There seems to be a problem with the iptv section, when you click on a channel it plays for about a minute before crashing. I suspect its an issue with the app, because it started right after the 17.0 update. Is there any way you can fix it?

**Comment by rapha3lhd** [comment]
We need help.. i can see whith the new verson 17.o or 17.1

**Comment by maximilize** [comment]
Thanks for reporting this issue. We found the bug and released a fix with version 0.17.2. This update should be applied automatically when you restart the app, or navigate to Settings -> Update.

To prevent such broken releases in the future, we plan to start a beta program.

**Comment by rapha3lhd** [comment]
Thks you for the help..keep up with good work..

A segunda, 27/07/2020, 00:43, max <notifications@github.com> escreveu:

**Comment by freddyumari** [comment]
Thank you for your help. This is a fantastic app, more grease to your elbow.
