### ISSUE TITLE
SUBTITLES OUT OF SYNC

### ISSUE THREAD

**Issue by triggggy** [watchedcom/watched-js#32]
Whenever I use subtitles, the subtitles show either before or after they are said. This becomes really annoying. Please fix the subtitles!

**Comment by maximilize** [comment]
You can adjust the subtitle delay in the video player settings. With this, you should be able to fix such issues.

**Comment by triggggy** [comment]
> You can adjust the subtitle delay in the video player settings. With this, you should be able to fix such issues.

Where can I find video player settings?
