### ISSUE TITLE
I downloaded the macOS version of WATCHED on my mac and whenever I try to play a server it says couldnt load plugin, please help.

### ISSUE THREAD

**Issue by lolawery5673** [watchedcom/watched-js#37]
Please describe your issue in as much detail as possible.

- **Only** post issues related to the WATCHED app or the WATCHED SDK.

- We do **not** give support for **3rd party addons**. Try to contact the addon creator.

- If you have an issue with one of [official addons](https://github.com/watchedcom) create an issue in the corresponding repo.

**Comment by maximilize** [comment]
We released an updated (v0.18.2) a few hours ago. You should receive the update when you start the app again. If the error still persists, please reopen this issue. Thank you.
