### ISSUE TITLE
Watched program for Windows Not Running

### ISSUE THREAD

**Issue by Akoakam** [watchedcom/watched-js#38]
When you visit the Watched.com with PC and after the download button, it shows it is available for Windows too.

But when you download the file and Install it on the computer, it never runs and shows the program on the screen.

Is it possible to walk me through your solutions and guide me to how to fix it?
Thanks for your time and work you put to create this product.

**Comment by maximilize** [comment]
We can't reproduce this issue. However, often it happens that virus scanners are blocking some apps, or causing issues when downloading, installing or using apps. So try to turn off your virus scanner.

**Comment by maximilize** [comment]
Since here is no feedback, I assume this issue is solved.
