### ISSUE TITLE
macOS not working

### ISSUE THREAD

**Issue by lolawery5673** [watchedcom/watched-js#39]
macOS version cant load plugin please help

**Comment by maximilize** [comment]
We just released an update to support older versions of macOS as well. When you start the app next time, the update should be applied.
If the problem still persists, please tell me your macOS version.

**Comment by BertrandCO** [comment]
Hello, 
new release still does not work on my mac and cannot load plugin.
Mac version is MacBook (13-inch, Aluminum, Late 2008) with Os 10.11.6
Thanks!

**Comment by maximilize** [comment]
You need at least macOS *High Sierra* which has the version number 10.13.
