### ISSUE TITLE
Windows version doesn't load some IPTV channels

### ISSUE THREAD

**Issue by pmk65** [watchedcom/watched-js#50]
I have both the Android an Windows version of Watched. Both connected to the same network/router. (Windows via cable and Android via WiFi)

On Android the IPTV channels are displayed almost instantly, but on Windows the exact same channels either takes minutes to appear or just shows the progress spinner forever.
Sometimes it helps switching to another channel and then back to the channel that didn't load at first, which seems to trigger a reload. But it's not 100% working either.
The problems occurs when I select Danish TV channels. I also tested it using German TV channels, but they doesn't seem to have the same problems.

Movies and Series works fine on Windows version.

**Comment by maximilize** [comment]
We tested our app on different platforms and everywhere it had the same outputs. It seems that your issues are related to some addons in the wild?
