### ISSUE TITLE
couldnt load plugin

### ISSUE THREAD

**Issue by ahgodbless** [watchedcom/watched-js#57]
need help want to watch something or anything and when it loads it says couldn't load plugin. im on pc

**Comment by maximilize** [comment]
I assume you are on a PC running Windows? We heard of users who face issues like yours, but so far we where not able to figure out what's the solution to this.

My guesses are:
- Missing support libraries like VC Rumtime or similar
- Some crazy anti virus apps running in background and influencing the system

Support to solve this error would be great
