### ISSUE TITLE
I have purchased the watched premium for indian channels before there were indian channels but now its not there so i want my money back!

### ISSUE THREAD

**Issue by theking40** [watchedcom/watched-js#69]
Please describe your issue in as much detail as possible.

- **Only** post issues related to the WATCHED app or the WATCHED SDK.

- We do **not** give support for **3rd party addons**. Try to contact the addon creator.

- If you have an issue with one of [official addons](https://github.com/watchedcom) create an issue in the corresponding repo.

**Comment by maximilize** [comment]
Please read the rules on posting issues. Thank you.

**Comment by theking40** [comment]
So what should i do?? I  want my money back
--
Sent from myMail for Android Monday, 02 November 2020, 05:18am +05:30 from max  notifications@github.com :
