### ISSUE TITLE
The movie "words on bathroom walls" doesn't have any sources

### ISSUE THREAD

**Issue by lich30** [watchedcom/watched-js#70]
Hoi yesterday I wanted to watch this movie that I couldn't find anywhere, so i searched it on Watched and it was there bu it didn't have sources and, in the case that you fix this, please add subtitles specially in spanish 👋😄

**Comment by maximilize** [comment]
Please read the rules regarding posting issues. If you have an issue with an official addon, please post this in the repository for this.
